spring:
  profiles:
    active: dev
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BUSINESS-USER
          uri: lb://business
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: BUSINESS-RESUME
          uri: lb://business
          predicates:
            - Path=/api/resume/**
          filters:
            - StripPrefix=1
        - id: BUSINESS-UPLOAD
          uri: lb://business
          predicates:
            - Path=/api/upload/**
          filters:
            - StripPrefix=1
        - id: BUSINESS-ROLE
          uri: lb://business
          predicates:
            - Path=/api/role/**
          filters:
            - StripPrefix=1
        - id: BUSINESS-PERMISSION
          uri: lb://business
          predicates:
            - Path=/api/permission/**
          filters:
            - StripPrefix=1
        - id: BUSINESS-ALBUM
          uri: lb://business
          predicates:
            - Path=/api/album/**
          filters:
            - StripPrefix=1

server:
  port: 端口号
