spring:
  cloud:
    inetutils:
      ignored-interfaces: eth.*
      preferred-networks: 公网 IP
    nacos:
      discovery:
        server-addr: 公网 IP:8848
  datasource:
    username: username
    password: password
  redis:
    host: 公网 IP
    port: 6379
